# Generated by Django 4.2.5 on 2023-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JaiMaApp', '0005_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='JaiMa/images/'),
        ),
    ]
